### PR TITLE
Release v1.0

### PR DESCRIPTION
**Pull request by lawrencerodrigues**
Requesting a Pull Request for merging my below changes into master branch :
1.Added a Operations.py file
2.Deleted Test-Copy.txt

### CODE REVIEW

**Comment by vasantverma** [comment]
Hey Lawrence,I have reviewed the changes that you have  done. Requested to add some more examples in Opeartions.py file

**Comment by lawrencerodrigues** [comment]
Added neccessary changes . Kindly review it

**Comment by vasantverma** [comment]
Hey lawrence, I have reviewed your changes and they are fine. Will merge the changes in master branch.

**Comment by vasantverma** [comment]
Successfully merged the changes into master branch.

**Pull request merged**
